### ISSUE TITLE
Падение Салют при получении json с max_lines=0

### ISSUE THREAD

**Issue by dbf256** [sberdevices/salute-issues#155]
**Где нашелся баг**: Приложение Салют
**Описание проблемы**: При попытке выставить max_lines=0 (по спецификации https://developer.sberdevices.ru/docs/ru/developer_tools/amp/smartapp_interface_elements#grid-card) приложение Салют падает
**Проблема воспроизводится у других пользователей?** не знаю.
**Дополнительная информация**: 

```
java.lang.IllegalArgumentException: lines should be positive, actual = 0
 at ru.sberbank.sdakit.messages.presentation.viewholders.measuring.TextViewMeasurer.c(SourceFile:6)
 at ru.sberbank.sdakit.messages.presentation.viewholders.measuring.TextViewMeasurer.a(SourceFile:5)
 at ru.sberbank.sdakit.messages.presentation.viewholders.measuring.TextViewMeasurer.b(SourceFile:3)
 at ru.sberbank.sdakit.messages.presentation.viewholders.greeting.GridCardMeasurer.a(SourceFile:1)
 at ru.sberbank.sdakit.messages.presentation.viewholders.greeting.GridCardMeasurer.b(SourceFile:1)
 at ru.sberbank.sdakit.messages.presentation.viewholders.greeting.GridCardMeasurer.c(SourceFile:3)
 at ru.sberbank.sdakit.messages.presentation.viewholders.greeting.GridCardViewHolder.X(SourceFile:5)
 at ru.sberbank.sdakit.messages.presentation.viewholders.greeting.GridCardViewHolder.R(SourceFile:1)
 at ru.sberbank.sdakit.messages.presentation.adapters.MessagesAdapterImpl.Q(SourceFile:1)
 at ru.sberbank.sdakit.messages.presentation.adapters.MessagesAdapterImpl.D(SourceFile:1)
 at androidx.recyclerview.widget.RecyclerView$Adapter.E(SourceFile:1)
 at androidx.recyclerview.widget.RecyclerView$Adapter.m(SourceFile:8)
 at androidx.recyclerview.widget.RecyclerView$Recycler.H(SourceFile:7)
 at androidx.recyclerview.widget.RecyclerView$Recycler.I(SourceFile:55)
 at androidx.recyclerview.widget.RecyclerView$Recycler.p(SourceFile:1)
 at androidx.recyclerview.widget.RecyclerView$Recycler.o(SourceFile:1)
 at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.d(SourceFile:3)
 at androidx.recyclerview.widget.LinearLayoutManager.u2(SourceFile:1)
 at androidx.recyclerview.widget.LinearLayoutManager.V1(SourceFile:9)
 at androidx.recyclerview.widget.LinearLayoutManager.Y0(SourceFile:65)
 at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:12)
 at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:9)
 at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:2)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
 at android.view.View.layout(View.java:20699)
at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
 at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
 at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
 at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
 at com.android.internal.policy.DecorView.onLayout(DecorView.java:774)
 at android.view.View.layout(View.java:20699)
 at android.view.ViewGroup.layout(ViewGroup.java:6198)
 at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2834)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2361)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1500)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7341)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1048)
 at android.view.Choreographer.doCallbacks(Choreographer.java:843)
 at android.view.Choreographer.doFrame(Choreographer.java:775)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1034)
 at android.os.Handler.handleCallback(Handler.java:873)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6882)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by Genenko-Svetlana** [comment]
@dbf256 Добрый день! Подскажите, пожалуйста, ОС и версию.

**Comment by dbf256** [comment]
Запускал под андроидом, версию не скажу т.к. пришлось переустановить, чтобы избавиться от ошибки. На последней не проверял.

**Comment by Genenko-Svetlana** [comment]
@dbf256 проверьте, пожалуйста. Если в новой версии ошибка не воспроизводится - закройте тикет.
